name: Publish to PyPI

on:
  workflow_call:
    inputs:
      repository:
        description: "GitHub repository"
        required: true
        type: string
      test_publish:
        description: "If true, publish to TestPyPI"
        required: false
        default: false
        type: boolean
    secrets:
      PYPI_TOKEN:
        required: true
      TEST_PYPI_TOKEN:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip

      - name: Install build tools
        run: |
          pip install build twine

      - name: Build package
        run: |
          python -m build

      - name: Publish package to TestPyPI or PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ inputs.test_publish == true && secrets.TEST_PYPI_TOKEN || secrets.PYPI_TOKEN }}
        run: |
          if [ "${{ inputs.test_publish }}" = "true" ]; then
            echo "Publicando no TestPyPI..."
            twine upload --repository-url https://test.pypi.org/legacy/ dist/* || echo "⚠️ Versão já existente no TestPyPI, ignorando erro."
          else
            echo "Publicando no PyPI..."
            twine upload dist/* || echo "⚠️ Versão já existente no PyPI, ignorando erro."
          fi
